# yaml-language-server: $schema=./winconfig.tasks.schema.json

### Appearance ###
SystemDarkMode: apply
AppDarkMode: revert

### Suggestions ###
DisableWindowsSuggestions: apply

### Taskbar ###
TaskbarAlignmentLeft: apply
EnableTaskbarEndTask: apply
HideTaskbarSearch: apply
HideTaskbarTaskView: apply
HideTaskbarWidgets: apply
RemoveCopilot: apply
ShowClockSeconds: apply
ShowMultiMonitorTaskbar: apply

### Desktop / Side Panel / Settings ###
HideDesktopRecycleBin: apply
ShowSidePanelClock: apply
HideSettingsSuggestions: apply

### Start Menu ###
DisableStartMenuBingSearch: apply
HideStartMenuRecommendations: apply
HideStartMenuAccountNotifications: apply
EnableGodMode: apply

### Explorer ###
ShowHiddenFiles: apply
ShowFileExtensions: apply
HideExplorerHome: apply
HideExplorerGallery: apply
DisableOneDrive: apply
DisableExplorerGroupView: apply
EnableExplorerRestoreLastSession: apply
DisableExplorerCheckBoxes: apply
HideExplorerRecentFiles: apply
HideExplorerFrequentFolders: apply

### Files ###
DisableShortcutsSuffix: apply
DisableUnsafeFileWarning: apply

### Context Menu ###
EnableClassicContextMenu: apply
DisableContextMenuLimit: apply
HideClipchampContextMenu: apply
HideEditWithPhotos: apply
HideEditWithPaint: apply
HideEditWithNotepad: apply
HideExtractAll: apply
HideOpenInWindowsTerminal: apply
HidePrint: apply
HideCompressedFolder: apply
HideSearchMsStore: apply
HideShare: apply
HideAddToFavorite: apply
HidePreviousVersions: apply
HideSendTo: apply
HideAddToLibrary: apply
HideGiveAccessTo: apply

### Mouse / Keyboard ###
DisableMouseAcceleration: apply
DisableF1HelpPage: apply
DisableStickyShift: apply
FastKeyRepeat: apply
DisableTouchPad: apply

### Sound ###
NoSystemSound: apply

### Startup / Background ###
DisableAutoDeleteTemp: apply
DisableXboxGameBar: apply
EnableWindowsRestoreLastSession: skip

### PowerPlan ###
EnableHighPowerPlan: apply
DisableMonitorTimeout: apply
